version: '3.8'

services:
  react-app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:3000"
    command: sh -c "npm install && npm run build && npx serve -s dist"
